# Generated by Django 5.2.4 on 2025-09-25 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpo', '0004_retailerreviewoffpo_fpobid'),
        ('retailer', '0003_retailerquoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpobid',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='retailer.retailerquoterequest'),
        ),
        migrations.AddField(
            model_name='retailerreviewoffpo',
            name='bid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fpo.fpobid'),
        ),
        migrations.AddField(
            model_name='retailerreviewoffpo',
            name='fpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_from_retailers', to='fpo.fpo'),
        ),
        migrations.AddField(
            model_name='retailerreviewoffpo',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailer.retailer'),
        ),
    ]
