# Generated by Django 5.2.4 on 2025-09-26 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_remove_farmerbid_farmer_remove_farmerbid_quote_and_more'),
        ('fpo', '0005_fpobid_quote_retailerreviewoffpo_bid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FPOQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(help_text='e.g., kg, quintal, ton', max_length=20)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('awarded', 'Awarded')], default='open', max_length=10)),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fpoquoterequest',
            name='accepted_bid',
        ),
        migrations.RemoveField(
            model_name='fpoquoterequest',
            name='fpo',
        ),
        migrations.RemoveField(
            model_name='retailerreviewoffpo',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='retailerreviewoffpo',
            name='fpo',
        ),
        migrations.RemoveField(
            model_name='retailerreviewoffpo',
            name='retailer',
        ),
        migrations.AlterField(
            model_name='fpobid',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='farmer.farmerquote'),
        ),
    ]
