# Generated by Django 5.2.4 on 2025-09-26 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_delete_farmerbid_delete_fporeviewoffarmer'),
        ('fpo', '0006_fpoquote_remove_fpoquoterequest_accepted_bid_and_more'),
        ('retailer', '0004_retailerbid_delete_retailerquoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='fpoquote',
            name='accepted_bid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for_fpo_quote', to='retailer.retailerbid'),
        ),
        migrations.AddField(
            model_name='fpoquote',
            name='fpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='fpo.fpo'),
        ),
        migrations.DeleteModel(
            name='FPOQuoteRequest',
        ),
        migrations.DeleteModel(
            name='RetailerReviewOfFPO',
        ),
    ]
