# Generated by Django 5.2.17 on 2026-08-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpo', '0009_fpo_inventory_lot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fpobid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=8, help_text='Price per unit', max_digits=18),
        ),
        migrations.AlterField(
            model_name='fpoquote',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='fpoquote',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
    ]
