# Generated by Django 5.2.17 on 2026-08-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('farmer', 'Farmer'), ('fpo', 'FPO'), ('retailer', 'Retailer')], max_length=20)),
                ('user_id', models.PositiveIntegerField()),
                ('trust_score', models.IntegerField(default=50, help_text='Calculated Trust Score (0-100)')),
                ('completed_transactions', models.PositiveIntegerField(default=0)),
                ('verified_activities', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reputation',
                'verbose_name_plural': 'Reputations',
                'ordering': ['-trust_score', '-updated_at'],
                'unique_together': {('user_role', 'user_id')},
            },
        ),
    ]
