# Generated by Django 5.2.4 on 2025-09-25 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpo', '0004_retailerreviewoffpo_fpobid'),
        ('retailer', '0002_retailer_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerQuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(help_text='e.g., kg, quintal, ton', max_length=20)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('awarded', 'Awarded')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for_retailer_quote', to='fpo.fpobid')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='retailer.retailer')),
            ],
        ),
    ]
