# Generated by Django 5.2.4 on 2025-09-26 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpo', '0006_fpoquote_remove_fpoquoterequest_accepted_bid_and_more'),
        ('retailer', '0003_retailerquoterequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('delivery_time_days', models.PositiveIntegerField()),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('transaction_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='fpo.fpoquote')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='retailer.retailer')),
            ],
        ),
        migrations.DeleteModel(
            name='RetailerQuoteRequest',
        ),
    ]
