# Generated by Django 5.2.17 on 2026-08-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0004_retailerbid_delete_retailerquoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='did',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='did_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
