# Generated by Django 5.2.17 on 2026-08-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0005_did_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailerbid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=8, help_text='Price per unit', max_digits=18),
        ),
    ]
