# Generated by Django 5.2.17 on 2026-08-14 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0002_retailerescrowtransaction'),
        ('farmer', '0014_alter_croppassport_quantity_and_more'),
        ('fpo', '0013_fpo_quote_available_quantity'),
        ('retailer', '0007_retailer_cart_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerInventoryLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('crop_category', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=18)),
                ('unit', models.CharField(max_length=20)),
                ('purchase_price_per_unit', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('status', models.CharField(default='in_stock', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop_passport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retailer_inventory_lots', to='farmer.croppassport')),
                ('escrow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retailer_inventory_lots', to='escrow.retailerescrowtransaction')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_inventory_lots', to='farmer.farmer')),
                ('fpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_inventory_lots', to='fpo.fpo')),
                ('inventory_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retailer_acquired_inventory_lots', to='fpo.fpoinventorylot')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_lots', to='retailer.retailer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
