# Generated by Django 5.2.17 on 2026-08-08 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0012_ai_quality_verification'),
        ('fpo', '0008_did_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escrow_id', models.PositiveIntegerField(blank=True, help_text='On-chain escrow ID from the smart contract', null=True)),
                ('contract_address', models.CharField(blank=True, help_text='Deployed FarmerChainEscrow contract address', max_length=42)),
                ('amount_eth', models.DecimalField(decimal_places=8, help_text='Escrow amount in ETH', max_digits=18)),
                ('status', models.CharField(choices=[('created', 'Created'), ('funded', 'Funded'), ('delivery_confirmed', 'Delivery Confirmed'), ('released', 'Released'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='created', max_length=20)),
                ('create_tx_hash', models.CharField(blank=True, help_text='Tx hash from createEscrow()', max_length=66, null=True)),
                ('deposit_tx_hash', models.CharField(blank=True, help_text='Tx hash from depositEscrow()', max_length=66, null=True)),
                ('delivery_tx_hash', models.CharField(blank=True, help_text='Tx hash from confirmDelivery()', max_length=66, null=True)),
                ('release_tx_hash', models.CharField(blank=True, help_text='Tx hash from releasePayment()', max_length=66, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_transactions', to='farmer.farmer')),
                ('fpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_transactions', to='fpo.fpo')),
                ('quote', models.OneToOneField(help_text='One escrow per accepted quote', on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='farmer.farmerquote')),
            ],
            options={
                'verbose_name': 'Escrow Transaction',
                'verbose_name_plural': 'Escrow Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
