# Generated by Django 5.2.17 on 2026-08-11 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0001_escrow_transaction'),
        ('fpo', '0008_did_fields'),
        ('retailer', '0005_did_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerEscrowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escrow_id', models.PositiveIntegerField(blank=True, help_text='On-chain escrow ID from the smart contract', null=True)),
                ('contract_address', models.CharField(blank=True, help_text='Deployed FarmerChainEscrow contract address', max_length=42)),
                ('amount_eth', models.DecimalField(decimal_places=8, help_text='Escrow amount in ETH', max_digits=18)),
                ('status', models.CharField(choices=[('created', 'Created'), ('funded', 'Funded'), ('delivery_confirmed', 'Delivery Confirmed'), ('released', 'Released'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='created', max_length=20)),
                ('create_tx_hash', models.CharField(blank=True, help_text='Tx hash from createEscrow() by FPO', max_length=66, null=True)),
                ('deposit_tx_hash', models.CharField(blank=True, help_text='Tx hash from depositEscrow() by Retailer', max_length=66, null=True)),
                ('delivery_tx_hash', models.CharField(blank=True, help_text='Tx hash from confirmDelivery() by FPO', max_length=66, null=True)),
                ('release_tx_hash', models.CharField(blank=True, help_text='Tx hash from releasePayment() by Retailer', max_length=66, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('fpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_escrows', to='fpo.fpo')),
                ('quote', models.OneToOneField(help_text='One escrow per accepted FPO quote', on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='fpo.fpoquote')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_escrows', to='retailer.retailer')),
            ],
            options={
                'verbose_name': 'Retailer Escrow Transaction',
                'verbose_name_plural': 'Retailer Escrow Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
