# Generated by Django 5.2.17 on 2026-09-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0002_retailerescrowtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowtransaction',
            name='agreed_price_inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final agreed total INR amount (may differ if negotiated discount applied; defaults to total_amount_inr)', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', help_text='INR commercial payment status — independent of blockchain escrow status', max_length=20),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='total_amount_inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='quantity × unit_price_inr — gross commercial value in INR', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='unit_price_inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Agreed price per unit in INR from the accepted bid', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='retailerescrowtransaction',
            name='agreed_price_inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final agreed total INR amount (may differ if negotiated discount applied; defaults to total_amount_inr)', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='retailerescrowtransaction',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', help_text='INR commercial payment status — independent of blockchain escrow status', max_length=20),
        ),
        migrations.AddField(
            model_name='retailerescrowtransaction',
            name='total_amount_inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='quantity × unit_price_inr — gross commercial value in INR', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='retailerescrowtransaction',
            name='unit_price_inr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Agreed price per unit in INR from the accepted retailer bid', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='amount_eth',
            field=models.DecimalField(decimal_places=8, help_text='Escrow amount in ETH — used for Sepolia blockchain settlement only', max_digits=18),
        ),
        migrations.AlterField(
            model_name='retailerescrowtransaction',
            name='amount_eth',
            field=models.DecimalField(decimal_places=8, help_text='Escrow amount in ETH — used for Sepolia blockchain settlement only', max_digits=18),
        ),
    ]
