# Generated by Django 5.2.4 on 2025-09-25 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_fporeviewoffarmer_farmerbid'),
        ('fpo', '0003_fpoquoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerbid',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='fpo.fpoquoterequest'),
        ),
        migrations.AddField(
            model_name='fporeviewoffarmer',
            name='bid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='farmer.farmerbid'),
        ),
        migrations.AddField(
            model_name='fporeviewoffarmer',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_from_fpos', to='farmer.farmer'),
        ),
        migrations.AddField(
            model_name='fporeviewoffarmer',
            name='fpo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpo.fpo'),
        ),
    ]
