# Generated by Django 5.2.4 on 2025-09-26 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_farmerbid_quote_fporeviewoffarmer_bid_and_more'),
        ('fpo', '0005_fpobid_quote_retailerreviewoffpo_bid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerbid',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='farmerbid',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='fporeviewoffarmer',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='fporeviewoffarmer',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='fporeviewoffarmer',
            name='fpo',
        ),
        migrations.CreateModel(
            name='FarmerQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(help_text='e.g., kg, quintal, ton', max_length=20)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('awarded', 'Awarded')], default='open', max_length=10)),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_bid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for_farmer_quote', to='fpo.fpobid')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='farmer.farmer')),
            ],
        ),
    ]
