# Generated by Django 5.2.4 on 2025-09-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_remove_farmerbid_farmer_remove_farmerbid_quote_and_more'),
        ('fpo', '0006_fpoquote_remove_fpoquoterequest_accepted_bid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FarmerBid',
        ),
        migrations.DeleteModel(
            name='FPOReviewOfFarmer',
        ),
    ]
