# Generated by Django 5.2.17 on 2026-08-08 05:01 (manually edited)
# Removed contract_address / contract_created_at operations — those
# columns already exist in the DB from a previous manual migration run.
# Only the DID fields and AlterField for status are applied here.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_delete_farmerbid_delete_fporeviewoffarmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='did',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='did_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
