# Generated by Django 5.2.17 on 2026-08-08 05:58 (manually edited)
# Removed AddField for contract_address / contract_created_at on FarmerQuote
# because those columns already exist in the DB from a prior manual run.
# AlterField for status also removed — existing value is already correct.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0008_backfill_dids'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=200)),
                ('crop_category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('quintal', 'Quintal'), ('ton', 'Ton'), ('litre', 'Litre'), ('piece', 'Piece'), ('dozen', 'Dozen')], default='kg', max_length=20)),
                ('cultivation_date', models.DateField()),
                ('harvest_date', models.DateField()),
                ('location', models.CharField(blank=True, help_text='Auto-filled from farmer city+state if left empty', max_length=200)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('minted', 'Minted')], default='registered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nft_token_id', models.CharField(blank=True, max_length=78, null=True)),
                ('nft_contract_address', models.CharField(blank=True, max_length=42, null=True)),
                ('nft_token_uri', models.CharField(blank=True, max_length=500, null=True)),
                ('nft_transaction_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('nft_minted_at', models.DateTimeField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_passports', to='farmer.farmer')),
            ],
            options={
                'verbose_name': 'Crop Passport',
                'verbose_name_plural': 'Crop Passports',
                'ordering': ['-created_at'],
            },
        ),
    ]
