# Generated by Django 5.2.17 on 2026-08-08 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0010_reconcile_farmerquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropPassportDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('document_type', models.CharField(choices=[('crop_image', 'Crop Image'), ('soil_report', 'Soil Report'), ('quality_report', 'Quality Report'), ('certification', 'Certification'), ('harvest_document', 'Harvest Document'), ('other', 'Other')], default='other', max_length=50)),
                ('ipfs_cid', models.CharField(max_length=255)),
                ('ipfs_uri', models.CharField(max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('crop_passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='farmer.croppassport')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='farmer.farmer')),
            ],
            options={
                'verbose_name': 'Crop Passport Document',
                'verbose_name_plural': 'Crop Passport Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
