# Generated by Django 5.2.17 on 2026-08-08 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0011_ipfs_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQualityVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_cid', models.CharField(max_length=255)),
                ('image_uri', models.CharField(max_length=300)),
                ('crop_detected', models.CharField(blank=True, max_length=200)),
                ('quality_grade', models.CharField(blank=True, choices=[('A', 'A — Excellent'), ('B', 'B — Good'), ('C', 'C — Acceptable'), ('D', 'D — Poor'), ('F', 'F — Unacceptable')], max_length=2)),
                ('quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('disease_detected', models.BooleanField(default=False)),
                ('disease_name', models.CharField(blank=True, max_length=200, null=True)),
                ('visible_defects', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('failure_reason', models.TextField(blank=True)),
                ('ai_provider', models.CharField(default='gemini-1.5-flash', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_verifications', to='farmer.croppassport')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_verifications', to='farmer.farmer')),
            ],
            options={
                'verbose_name': 'AI Quality Verification',
                'verbose_name_plural': 'AI Quality Verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
