# Generated by Django 5.2.17 on 2026-08-11 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0012_ai_quality_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerquote',
            name='crop_passport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='farmer.croppassport'),
        ),
    ]
