# Generated by Django 5.2.17 on 2026-08-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0013_farmerquote_crop_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croppassport',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name='farmerquote',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='farmerquote',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='farmerquote',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
    ]
