# Generated by Django 5.2.17 on 2026-08-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0014_alter_croppassport_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='croppassport',
            name='available_quantity',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='croppassport',
            name='sold_quantity',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='croppassport',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('minted', 'Minted'), ('sold', 'Sold / Completed')], default='registered', max_length=20),
        ),
    ]
